### ISSUE TITLE
2.0 doesnt seem to exist

### ISSUE THREAD

**Issue by rumpranger** [Sorien/silex-dbal-profiler#4]
Any plans to release 2.0? 

Cheers

**Comment by Sorien** [comment]
after silex 2.0 is out ;) ...  

Edit: it looks like there is some problem with composer package config ... i'll try to solve it

**Comment by Sorien** [comment]
you have to specify minimum stability like

```
{
    "require": {
        "sorien/silex-dbal-profiler": "2.0.*@dev"
    },
    "minimum-stability": "dev",
    "autoload": {
        "psr-0": {"": "src/"}
    }
}
```

**Comment by rumpranger** [comment]
That's not solving it for us (we're running the 2.0@dev from the skeleton repo https://github.com/silexphp/Silex-Skeleton): 
`Problem 1
    - Installation request for fabpot/silex-skeleton 2.0.x-dev -> satisfiable by fabpot/silex-skeleton[2.0.x-dev].
    - fabpot/silex-skeleton 2.0.x-dev requires sorien/silex-dbal-profiler ~2.0@dev -> no matching package found.`

**Comment by Sorien** [comment]
try to test now ... i'm really not sure how to solve this version hell :/

**Comment by rumpranger** [comment]
We got it to work by changing the composer statement to match your branch alias:
composer require sorien/silex-dbal-profiler dev-master
Ideally we would pull from a ~stable~ version rather than the master.

BTW: Great provider, thanks!

**Comment by mathroc** [comment]
Silex 2 is out !

**Comment by Sorien** [comment]
I don't have any working setup right now, can you try it?

**Comment by mathroc** [comment]
I've been using this package with silex "master" for a few months and now with silex-2.0. it's working great! :+1:
