### ISSUE TITLE
DBAL Profiler doesn't work with PHPEngine Templating

### ISSUE THREAD

**Issue by scruffycoderofficial** [Sorien/silex-dbal-profiler#7]
I have setup my Silex application such that it uses the PHPEngine instead of Twig and I have just installed this library but it is failing.

Below is a message I get:

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Identifier "twig" is not defined.'
InvalidArgumentException: Identifier "twig" is not defined.

In my bootstrap file I have included the following service providers as shown below:

if(ENV != 'LIVE'){

   $app->register(new Silex\Provider\WebProfilerServiceProvider());
   $app->register(new Sorien\Provider\DoctrineProfilerServiceProvider());
 }

Is the a tweak I can perform without touching this library to make it work with php?

**Comment by Sorien** [comment]
it's just extension/module to https://github.com/silexphp/Silex-WebProfiler and i don't think you can run silex webprofiller without twig
